scoreboard objectives add posX dummy
scoreboard objectives add posY dummy
scoreboard objectives add posZ dummy 
scoreboard objectives add var dummy
scoreboard objectives add temp dummy
scoreboard objectives add test dummy
scoreboard objectives add 异界分数 dummy
scoreboard objectives add homex dummy
scoreboard objectives add homey dummy
scoreboard objectives add homez dummy
scoreboard objectives add backx dummy
scoreboard objectives add backy dummy
scoreboard objectives add backz dummy
scoreboard objectives add 菜单 stat.useItem.minecraft.carrot_on_a_stick
scoreboard objectives add cd trigger
scoreboard objectives add ch trigger
scoreboard objectives add ely trigger
scoreboard objectives add book trigger
scoreboard objectives add 花粉 dummy
scoreboard objectives add 蓝晶 dummy
scoreboard objectives add 花粉 dummy
scoreboard objectives add 花粉 dummy
scoreboard objectives add leaveGame stat.leaveGame
scoreboard objectives add backLeaveGame stat.leaveGame
scoreboard objectives add hurtPlayerCount dummy
scoreboard objectives add 惩罚次数 dummy
scoreboard objectives add deathCount deathCount
scoreboard objectives add sign dummy
scoreboard objectives add cs trigger
scoreboard objectives add tr trigger

