function login:config/load unless @s[tag=$loginLoaded]
tellraw @s ["当前登录模块配置："]
tellraw @s [{"text":"已禁用的项目:","color":"red"}]
tellraw @s[tag=-loginStd] [{"text":"- loginStd 标准化登录"}]
tellraw @s[tag=-stdStatus] [{"text":"- stdStatus 标准化登录.状态（药水效果等）"}]
tellraw @s[tag=-stdGift] [{"text":"- stdGift 标准化登录.礼包"}]
tellraw @s[tag=-stdUidGift] [{"text":"- stdUidGift 标准化登录.特定uid区段礼包"}]
tellraw @s[tag=-stdSpawn] [{"text":"- stdSpawn 标准化登录.自定义出生点"}]
tellraw @s[tag=-stdTextSound] [{"text":"- stdTextSound 标准化登录.声音和文字效果"}]
tellraw @s[tag=-initUid] [{"text":"- initUid 初始化uid"}]

tellraw @s [{"text":"已开启的项目:","color":"green"}]
tellraw @s[tag=!-loginStd] [{"text":"- loginStd 标准化登录"}]
tellraw @s[tag=!-stdStatus] [{"text":"- stdStatus 标准化登录.状态（药水效果等）"}]
tellraw @s[tag=!-stdGift] [{"text":"- stdGift 标准化登录.礼包"}]
tellraw @s[tag=!-stdUidGift] [{"text":"- stdUidGift 标准化登录.特定uid区段礼包"}]
tellraw @s[tag=!-stdSpawn] [{"text":"- stdSpawn 标准化登录.自定义出生点"}]
tellraw @s[tag=!-stdTextSound] [{"text":"- stdTextSound 标准化登录.声音和文字效果"}]
tellraw @s[tag=!-initUid] [{"text":"- initUid 初始化uid"}]