tellraw @s ["§a----------------------------------------------------"]
tellraw @s ["§a"]
tellraw @s ["§a  [1] [2] [3]"]
tellraw @s ["§a"]
tellraw @s ["§a  [3] [4] [5]"]
tellraw @s ["§a"]
tellraw @s ["§a  [6] [7] [8] "]
tellraw @s ["§a"]
tellraw @s ["§a银行面板:"]
tellraw @s ["§a银行面板:"]
tellraw @s ["§a银行面板:"]