tellraw @s ["§6--- 显示服务器帮助的总8页中的第1页（/trigger hlep set <页码>） ---"]
tellraw @s ["§a设置领地： /trigger ld set 1"]
tellraw @s ["§a返回领地： /trigger ld set -1"]
tellraw @s ["§a打开领地管理面板： /trigger ld_gl set 1"]
tellraw @s ["§a返回主城： /trigger cd set 1"]
tellraw @s ["§a设置重生点： /trigger cd set 3"]
tellraw @s ["§a自刎： /trigger cd set 6"]
tellraw @s ["§6小提示：在输入，命令时可以使用 <tab> 键来自动补全命令或参数"]