give @s minecraft:cooked_beef 64 0
give @s minecraft:white_shulker_box 1 0 {display:{Name:"新手盒子"}}
give @s minecraft:yellow_shulker_box 1 0 {display:{Name:"新手盒子"}}

give @s minecraft:white_shulker_box 1 0 {display:{Name:"§b❆§a新手礼包",Lore:["§6〓〓〓〓〓〓〓〓〓","§a➤§b主城随机传送后","§d❀§e右键地面打开"]},BlockEntityTag:{Items:[{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:0b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:1b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:2b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:3b},{id:"minecraft:chainmail_helmet",Count:1b,Damage:0s,tag:{ench:[{id:34,lvl:3}]},Slot:4b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:5b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:6b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:7b},{id:"minecraft:cooked_porkchop",Count:1b,Damage:0s,Slot:8b},{id:"minecraft:planks",Count:64b,Damage:0s,Slot:9b},{id:"minecraft:wheat_seeds",Count:1b,Damage:0s,Slot:10b},{id:"minecraft:reeds",Count:1b,Damage:0s,Slot:11b},{id:"minecraft:chainmail_chestplate",Count:1b,Damage:0s,tag:{ench:[{id:34,lvl:3}]},Slot:12b},{id:"minecraft:chainmail_leggings",Count:1b,Damage:0s,tag:{ench:[{id:34,lvl:3}]},Slot:13b},{id:"minecraft:chainmail_boots",Count:1b,Damage:0s,tag:{ench:[{id:34,lvl:3}]},Slot:14b},{id:"minecraft:dye",Count:1b,Damage:3s,Slot:15b},{id:"minecraft:pumpkin_seeds",Count:1b,Damage:0s,Slot:16b},{id:"minecraft:planks",Count:64b,Damage:0s,Slot:17b},{id:"minecraft:melon_seeds",Count:1b,Damage:0s,Slot:18b},{id:"minecraft:carrot",Count:1b,Damage:0s,Slot:19b},{id:"minecraft:potato",Count:1b,Damage:0s,Slot:20b},{id:"minecraft:iron_sword",Count:1b,Damage:0s,tag:{ench:[{id:17,lvl:3},{id:18,lvl:3},{id:34,lvl:3}]},Slot:21b},{id:"minecraft:iron_pickaxe",Count:1b,Damage:0s,tag:{ench:[{id:32,lvl:3},{id:34,lvl:3}]},Slot:22b},{id:"minecraft:iron_shovel",Count:1b,Damage:0s,tag:{ench:[{id:32,lvl:3},{id:34,lvl:3}]},Slot:23b},{id:"minecraft:beetroot_seeds",Count:1b,Damage:0s,Slot:24b},{id:"minecraft:sapling",Count:1b,Damage:0s,Slot:25b},{id:"minecraft:double_plant",Count:1b,Damage:0s,tag:{AttributeModifiers:[{Operation:0,Amount:-0.05,UUIDLeast:1L,UUIDMost:1L,Slot:mainhand,AttributeName:"generic.movementSpeed",Name:"CBC"}],display:{Name:"§a☘§6中子素§a☘",Lore:["§6〓〓〓〓〓〓〓〓〓","§c⚠§b蕴含强大能量","§a✔§e可用来收获更多庄稼"]},ench:[{id:35,lvl:5}]},Slot:26b}]}}
#give @s minecraft:carrot_on_a_stick 1 0 {caiDan:1b,display:{Name:"§e胡萝卜§b菜单",Lore:["§6〓〓〓〓〓〓〓〓〓〓〓","§a➤§b右键即可打开","§d✿§e书本菜单需要自己购买§d✿"]}}

give @s minecraft:slime_ball 1 0 {menuOpen:1b,display:{Name:"§c✿§b紫罗兰§a§d传§e送§3珠",Lore:["§6==============§a▼","§e初始的传送机","§6按Q键可使用§7§l<<"]},ench:[{id:16s,lvl:5s},{id:22s,lvl:5s}],AttributeModifiers:[{AttributeName:"generic.movementSpeed",Name:"noName",Amount:0.02d,Operation:0,UUIDMost:6474728772828391L,UUIDLeast:6474728772828391L,Slot:mainhand}]}



