scoreboard players reset ch
scoreboard players reset cd
scoreboard players reset cs
scoreboard players reset ld
scoreboard players reset ld_gl
scoreboard players reset home_set
scoreboard players reset home_back
scoreboard players reset home_remove
scoreboard players reset home_list
scoreboard players reset fly
scoreboard players reset tpa
scoreboard players reset menu
scoreboard players reset help
scoreboard players reset tpa
scoreboard players reset tpa_trigger
scoreboard players reset ling_di_mi_ma
