execute @s[score_xshopId_min=1,score_xshopId=1] ~ ~ ~ function xshop:items/1
execute @s[score_xshopId_min=2,score_xshopId=2] ~ ~ ~ function xshop:items/2
execute @s[score_xshopId_min=3,score_xshopId=3] ~ ~ ~ function xshop:items/3
execute @s[score_xshopId_min=4,score_xshopId=4] ~ ~ ~ function xshop:items/4
execute @s[score_xshopId_min=5,score_xshopId=5] ~ ~ ~ function xshop:items/5
execute @s[score_xshopId_min=6,score_xshopId=6] ~ ~ ~ function xshop:items/6
execute @s[score_xshopId_min=7,score_xshopId=7] ~ ~ ~ function xshop:items/7
execute @s[score_xshopId_min=8,score_xshopId=8] ~ ~ ~ function xshop:items/8
execute @s[score_xshopId_min=9,score_xshopId=9] ~ ~ ~ function xshop:items/9
execute @s[score_xshopId_min=10,score_xshopId=10] ~ ~ ~ function xshop:items/10
execute @s[score_xshopId_min=11,score_xshopId=11] ~ ~ ~ function xshop:items/11
execute @s[score_xshopId_min=12,score_xshopId=12] ~ ~ ~ function xshop:items/12
execute @s[score_xshopId_min=13,score_xshopId=13] ~ ~ ~ function xshop:items/13
execute @s[score_xshopId_min=14,score_xshopId=14] ~ ~ ~ function xshop:items/14
execute @s[score_xshopId_min=15,score_xshopId=15] ~ ~ ~ function xshop:items/15
execute @s[score_xshopId_min=16,score_xshopId=16] ~ ~ ~ function xshop:items/16
execute @s[score_xshopId_min=17,score_xshopId=17] ~ ~ ~ function xshop:items/17
execute @s[score_xshopId_min=18,score_xshopId=18] ~ ~ ~ function xshop:items/test

