scoreboard players reset @s job:sj
#法师master 5000 8000 10000 15000
scoreboard players tag @s[tag=master] add master:sj
execute @s[tag=master:sj,score_lv_min=1,score_lv=1] ~ ~ ~ function job:升级/master1→2
execute @s[tag=master:sj,score_lv_min=2,score_lv=2] ~ ~ ~ function job:升级/master2→3
execute @s[tag=master:sj,score_lv_min=3,score_lv=3] ~ ~ ~ function job:升级/master3→4
execute @s[tag=master:sj,score_lv_min=4,score_lv=4] ~ ~ ~ function job:升级/master4→5
tellraw @s[tag=master:sj,score_lv_min=5,score_lv=5] [{"text":"§6【Master】  §c您已到满级5级，请等待下次更新！"}]
#战士soldier
scoreboard players tag @s[tag=soldier] add soldier:sj
execute @s[tag=soldier:sj,score_lv_min=1,score_lv=1] ~ ~ ~ function job:升级/soldier1→2
execute @s[tag=soldier:sj,score_lv_min=2,score_lv=2] ~ ~ ~ function job:升级/soldier2→3
execute @s[tag=soldier:sj,score_lv_min=3,score_lv=3] ~ ~ ~ function job:升级/soldier3→4
execute @s[tag=soldier:sj,score_lv_min=4,score_lv=4] ~ ~ ~ function job:升级/soldier4→5
execute @s[tag=soldier:sj,score_lv_min=5,score_lv=5] ~ ~ ~ function job:升级/soldier5→6
execute @s[tag=soldier:sj,score_lv_min=6,score_lv=6] ~ ~ ~ function job:升级/soldier6→7
execute @s[tag=soldier:sj,score_lv_min=7,score_lv=7] ~ ~ ~ function job:升级/soldier7→8
execute @s[tag=soldier:sj,score_lv_min=8,score_lv=8] ~ ~ ~ function job:升级/soldier8→9
execute @s[tag=soldier:sj,score_lv_min=9,score_lv=9] ~ ~ ~ function job:升级/soldier9→10
execute @s[tag=soldier:sj,score_lv_min=10,score_lv=10] ~ ~ ~ function job:升级/soldier10→11
execute @s[tag=soldier:sj,score_lv_min=11,score_lv=11] ~ ~ ~ function job:升级/soldier11→12
execute @s[tag=soldier:sj,score_lv_min=12,score_lv=12] ~ ~ ~ function job:升级/soldier12→13
execute @s[tag=soldier:sj,score_lv_min=13,score_lv=13] ~ ~ ~ function job:升级/soldier13→14
execute @s[tag=soldier:sj,score_lv_min=14,score_lv=14] ~ ~ ~ function job:升级/soldier14→15
execute @s[tag=soldier:sj,score_lv_min=15,score_lv=15] ~ ~ ~ function job:升级/soldier15→16
execute @s[tag=soldier:sj,score_lv_min=16,score_lv=16] ~ ~ ~ function job:升级/soldier16→17
execute @s[tag=soldier:sj,score_lv_min=17,score_lv=17] ~ ~ ~ function job:升级/soldier17→18
execute @s[tag=soldier:sj,score_lv_min=18,score_lv=18] ~ ~ ~ function job:升级/soldier18→19
execute @s[tag=soldier:sj,score_lv_min=19,score_lv=19] ~ ~ ~ function job:升级/soldier19→20
execute @s[tag=soldier:sj,score_lv_min=20,score_lv=20] ~ ~ ~ function job:升级/soldier20→21
execute @s[tag=soldier:sj,score_lv_min=21,score_lv=21] ~ ~ ~ function job:升级/soldier21→22
execute @s[tag=soldier:sj,score_lv_min=22,score_lv=22] ~ ~ ~ function job:升级/soldier22→23
execute @s[tag=soldier:sj,score_lv_min=23,score_lv=23] ~ ~ ~ function job:升级/soldier23→24
execute @s[tag=soldier:sj,score_lv_min=24,score_lv=24] ~ ~ ~ function job:升级/soldier24→25
execute @s[tag=soldier:sj,score_lv_min=25,score_lv=25] ~ ~ ~ function job:升级/soldier25→26
execute @s[tag=soldier:sj,score_lv_min=26,score_lv=26] ~ ~ ~ function job:升级/soldier26→27
execute @s[tag=soldier:sj,score_lv_min=27,score_lv=27] ~ ~ ~ function job:升级/soldier27→28
execute @s[tag=soldier:sj,score_lv_min=28,score_lv=28] ~ ~ ~ function job:升级/soldier28→29
execute @s[tag=soldier:sj,score_lv_min=29,score_lv=29] ~ ~ ~ function job:升级/soldier29→30
execute @s[tag=soldier:sj,score_lv_min=30,score_lv=30] ~ ~ ~ function job:升级/soldier30→31
execute @s[tag=soldier:sj,score_lv_min=31,score_lv=31] ~ ~ ~ function job:升级/soldier31→32
execute @s[tag=soldier:sj,score_lv_min=32,score_lv=32] ~ ~ ~ function job:升级/soldier32→33
execute @s[tag=soldier:sj,score_lv_min=33,score_lv=33] ~ ~ ~ function job:升级/soldier33→34
execute @s[tag=soldier:sj,score_lv_min=34,score_lv=34] ~ ~ ~ function job:升级/soldier34→35
execute @s[tag=soldier:sj,score_lv_min=35,score_lv=35] ~ ~ ~ function job:升级/soldier35→36
execute @s[tag=soldier:sj,score_lv_min=36,score_lv=36] ~ ~ ~ function job:升级/soldier36→37
execute @s[tag=soldier:sj,score_lv_min=37,score_lv=37] ~ ~ ~ function job:升级/soldier37→38
execute @s[tag=soldier:sj,score_lv_min=38,score_lv=38] ~ ~ ~ function job:升级/soldier38→39
execute @s[tag=soldier:sj,score_lv_min=39,score_lv=39] ~ ~ ~ function job:升级/soldier39→40
execute @s[tag=soldier:sj,score_lv_min=40,score_lv=40] ~ ~ ~ function job:升级/soldier40→41
execute @s[tag=soldier:sj,score_lv_min=41,score_lv=41] ~ ~ ~ function job:升级/soldier41→42
execute @s[tag=soldier:sj,score_lv_min=42,score_lv=42] ~ ~ ~ function job:升级/soldier42→43
execute @s[tag=soldier:sj,score_lv_min=43,score_lv=43] ~ ~ ~ function job:升级/soldier43→44
execute @s[tag=soldier:sj,score_lv_min=44,score_lv=44] ~ ~ ~ function job:升级/soldier44→45
execute @s[tag=soldier:sj,score_lv_min=45,score_lv=45] ~ ~ ~ function job:升级/soldier45→46
execute @s[tag=soldier:sj,score_lv_min=46,score_lv=46] ~ ~ ~ function job:升级/soldier46→47
execute @s[tag=soldier:sj,score_lv_min=47,score_lv=47] ~ ~ ~ function job:升级/soldier47→48
execute @s[tag=soldier:sj,score_lv_min=48,score_lv=48] ~ ~ ~ function job:升级/soldier48→49
execute @s[tag=soldier:sj,score_lv_min=49,score_lv=49] ~ ~ ~ function job:升级/soldier49→50
tellraw @s[tag=soldier:sj,score_lv_min=50,score_lv=50] [{"text":"§6【Soldier】  §c您已到满级50级，请等待下次更新！"}]
#弓箭手archer
scoreboard players tag @s[tag=archer] add archer:sj
execute @s[tag=archer:sj,score_lv_min=1,score_lv=1] ~ ~ ~ function job:升级/archer1→2
execute @s[tag=archer:sj,score_lv_min=2,score_lv=2] ~ ~ ~ function job:升级/archer2→3
execute @s[tag=archer:sj,score_lv_min=3,score_lv=3] ~ ~ ~ function job:升级/archer3→4
execute @s[tag=archer:sj,score_lv_min=4,score_lv=4] ~ ~ ~ function job:升级/archer4→5
execute @s[tag=archer:sj,score_lv_min=5,score_lv=5] ~ ~ ~ function job:升级/archer5→6
execute @s[tag=archer:sj,score_lv_min=6,score_lv=6] ~ ~ ~ function job:升级/archer6→7
execute @s[tag=archer:sj,score_lv_min=7,score_lv=7] ~ ~ ~ function job:升级/archer7→8
execute @s[tag=archer:sj,score_lv_min=8,score_lv=8] ~ ~ ~ function job:升级/archer8→9
execute @s[tag=archer:sj,score_lv_min=9,score_lv=9] ~ ~ ~ function job:升级/archer9→10
execute @s[tag=archer:sj,score_lv_min=10,score_lv=10] ~ ~ ~ function job:升级/archer10→11
execute @s[tag=archer:sj,score_lv_min=11,score_lv=11] ~ ~ ~ function job:升级/archer11→12
execute @s[tag=archer:sj,score_lv_min=12,score_lv=12] ~ ~ ~ function job:升级/archer12→13
execute @s[tag=archer:sj,score_lv_min=13,score_lv=13] ~ ~ ~ function job:升级/archer13→14
execute @s[tag=archer:sj,score_lv_min=14,score_lv=14] ~ ~ ~ function job:升级/archer14→15
execute @s[tag=archer:sj,score_lv_min=15,score_lv=15] ~ ~ ~ function job:升级/archer15→16
execute @s[tag=archer:sj,score_lv_min=16,score_lv=16] ~ ~ ~ function job:升级/archer16→17
execute @s[tag=archer:sj,score_lv_min=17,score_lv=17] ~ ~ ~ function job:升级/archer17→18
execute @s[tag=archer:sj,score_lv_min=18,score_lv=18] ~ ~ ~ function job:升级/archer18→19
execute @s[tag=archer:sj,score_lv_min=19,score_lv=19] ~ ~ ~ function job:升级/archer19→20
execute @s[tag=archer:sj,score_lv_min=20,score_lv=20] ~ ~ ~ function job:升级/archer20→21
execute @s[tag=archer:sj,score_lv_min=21,score_lv=21] ~ ~ ~ function job:升级/archer21→22
execute @s[tag=archer:sj,score_lv_min=22,score_lv=22] ~ ~ ~ function job:升级/archer22→23
execute @s[tag=archer:sj,score_lv_min=23,score_lv=23] ~ ~ ~ function job:升级/archer23→24
execute @s[tag=archer:sj,score_lv_min=24,score_lv=24] ~ ~ ~ function job:升级/archer24→25
execute @s[tag=archer:sj,score_lv_min=25,score_lv=25] ~ ~ ~ function job:升级/archer25→26
execute @s[tag=archer:sj,score_lv_min=26,score_lv=26] ~ ~ ~ function job:升级/archer26→27
execute @s[tag=archer:sj,score_lv_min=27,score_lv=27] ~ ~ ~ function job:升级/archer27→28
execute @s[tag=archer:sj,score_lv_min=28,score_lv=28] ~ ~ ~ function job:升级/archer28→29
execute @s[tag=archer:sj,score_lv_min=29,score_lv=29] ~ ~ ~ function job:升级/archer29→30
execute @s[tag=archer:sj,score_lv_min=30,score_lv=30] ~ ~ ~ function job:升级/archer30→31
execute @s[tag=archer:sj,score_lv_min=31,score_lv=31] ~ ~ ~ function job:升级/archer31→32
execute @s[tag=archer:sj,score_lv_min=32,score_lv=32] ~ ~ ~ function job:升级/archer32→33
execute @s[tag=archer:sj,score_lv_min=33,score_lv=33] ~ ~ ~ function job:升级/archer33→34
execute @s[tag=archer:sj,score_lv_min=34,score_lv=34] ~ ~ ~ function job:升级/archer34→35
execute @s[tag=archer:sj,score_lv_min=35,score_lv=35] ~ ~ ~ function job:升级/archer35→36
execute @s[tag=archer:sj,score_lv_min=36,score_lv=36] ~ ~ ~ function job:升级/archer36→37
execute @s[tag=archer:sj,score_lv_min=37,score_lv=37] ~ ~ ~ function job:升级/archer37→38
execute @s[tag=archer:sj,score_lv_min=38,score_lv=38] ~ ~ ~ function job:升级/archer38→39
execute @s[tag=archer:sj,score_lv_min=39,score_lv=39] ~ ~ ~ function job:升级/archer39→40
execute @s[tag=archer:sj,score_lv_min=40,score_lv=40] ~ ~ ~ function job:升级/archer40→41
execute @s[tag=archer:sj,score_lv_min=41,score_lv=41] ~ ~ ~ function job:升级/archer41→42
execute @s[tag=archer:sj,score_lv_min=42,score_lv=42] ~ ~ ~ function job:升级/archer42→43
execute @s[tag=archer:sj,score_lv_min=43,score_lv=43] ~ ~ ~ function job:升级/archer43→44
execute @s[tag=archer:sj,score_lv_min=44,score_lv=44] ~ ~ ~ function job:升级/archer44→45
execute @s[tag=archer:sj,score_lv_min=45,score_lv=45] ~ ~ ~ function job:升级/archer45→46
execute @s[tag=archer:sj,score_lv_min=46,score_lv=46] ~ ~ ~ function job:升级/archer46→47
execute @s[tag=archer:sj,score_lv_min=47,score_lv=47] ~ ~ ~ function job:升级/archer47→48
execute @s[tag=archer:sj,score_lv_min=48,score_lv=48] ~ ~ ~ function job:升级/archer48→49
execute @s[tag=archer:sj,score_lv_min=49,score_lv=49] ~ ~ ~ function job:升级/archer49→50
tellraw @s[tag=archer:sj,score_lv_min=50,score_lv=50] [{"text":"§6【archer】  §c您已到满级50级，请等待下次更新！"}]