scoreboard players enable @a cs
scoreboard players enable @a book
scoreboard players enable @a ch
scoreboard players enable @a ely
scoreboard players enable @a 随机传送
scoreboard players enable @a 高级商品
scoreboard players enable @a cd
scoreboard players enable @a 称号
scoreboard players enable @a 圈地
scoreboard players enable @a tr
scoreboard players enable @a 彩嘌号码
